services:
  - type: web
    name: ferme-ia-ultra-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: OSINT_KEYWORDS
        sync: false
      - key: RUN_OSINT_ON_BOOT
        sync: false
      - key: HEARTBEAT_SECONDS
        sync: false
      - key: OSINT_INTERVAL_SECONDS
        sync: false
      - key: TOR_SOCKS_URL
        sync: false
